### ISSUE TITLE
Mbin support?

### ISSUE THREAD

**Issue by melroy89** [jwr1/interstellar#20]
### Describe the feature you'd like to request

Your project description only mentions Kbin. But hopefully it will support [Mbin](https://github.com/MbinOrg/mbin) as well (now and in the future)? If so, please update your 'about' section in GitHub as well as your Readme file.

Mbin has almost the same API for now. See also: https://kbin.melroy.org/api/docs. We even provide an `info` endpoint so you know it's mbin: https://kbin.melroy.org/api/info (too bad Kbin doesn't have this yet, so in the meanwhile you can use the AP nodeinfo spec: https://kbin.melroy.org/nodeinfo/2.1). Allowing you to see either the software is using either kbin or mbin.

**Comment by jwr1** [comment]
Yes, it definitely supports Mbin; I guess I should have made that more clear. I'll update the descriptions when I get a chance. Since the APIs are practically the same, I just assumed that Mbin support would be implied. I even have two Mbin servers in the recommended instances section (including yours):

![image](https://github.com/jwr1/interstellar/assets/47087725/85295971-cc2d-44ef-9f35-0360a7862f3a)
