### ISSUE TITLE
How do you share posts?

### ISSUE THREAD

**Issue by KeronCyst** [jwr1/interstellar#58]
### Describe the feature

I see no "share" button in the app. I have to open each article that I wanna share with friends in a browser and then copy the link from a browser.

**Comment by jwr1** [comment]
Unfortunately, there's no share feature yet. I'll see if I can look into adding it.

**Comment by evanfoster** [comment]
I'd also love this feature. Previously, I was using the `Copy Link` button with Android's new clipboard feature. It looks like that whole system has been reworked to remove the modal popup which got rid of the `Copy Link` button. I'm a big fan of the new design (since it lets you get straight through to the thing you want to look at, it's much more streamlined!), but now it's a bit harder to get a link to share.

Thanks for developing this app and doing the work to run kbin.earth!

**Comment by jwr1** [comment]
> I'd also love this feature. Previously, I was using the `Copy Link` button with Android's new clipboard feature. It looks like that whole system has been reworked to remove the modal popup which got rid of the `Copy Link` button. I'm a big fan of the new design (since it lets you get straight through to the thing you want to look at, it's much more streamlined!), but now it's a bit harder to get a link to share.
> 
> Thanks for developing this app and doing the work to run kbin.earth! I really appreciate what you're doing.

Thanks :)
You actually can still view that modal with the copy button though. All you have to do is long press or right click on the post link button with the URL. That modal is probably where I'll add the share button as well.

**Comment by jwr1** [comment]
Oh wow, thanks @evanfoster; I just saw your sponsorship! I'll definitely try to prioritize this for the next update :)

**Comment by evanfoster** [comment]
> Oh wow, thanks @evanfoster; I just saw your sponsorship! I'll definitely try to prioritize this for the next update :)

No rush! I didn't do that to try to rush this feature or anything, I've just been trying to support the people hosting fediverse stuff (since hosting isn't free and your time is valuable). I was supporting Ernest back when I was using kbin.social, and I just realized I hadn't continued that support when I switched to kbin.earth (plus, the incredible work you've been doing with Interstellar). It's good to know it's on your radar, but please don't delay other work you'd rather be doing on my account.

**Comment by jwr1** [comment]
Complete in c224beb5e51dee8766141f9beb59906b6d5af094 and c101705622ac8d4d4b028503872c9b542b2e5a31.

Once released, you will be able to:

- Share posts and comments by pressing the Share button in the overflow menu.
- Share post Links by long pressing or right-clicking the link, then pressing the Share button.
- Share full images by pressing the image for full screen, then tapping the share icon in the top right corner.
- Share full videos by tapping the share icon in the top right corner of the player.
