### ISSUE TITLE
The feed action breaks a lot of things

### ISSUE THREAD

**Issue by FitikWasTaken** [jwr1/interstellar#77]
### Describe the bug

In feed actions I have "Set filter" and "Set type" set like that
![Screenshot_20241214-055345](https://github.com/user-attachments/assets/0dd36a3c-0f92-491a-8f79-628c96a9462a)

My default sorting for Threads is "Hot" and for Microblogs is "New", however when i change to the Microblogging view it's still has "Hot" sorting 

When I change sorting type on one it also applies to both (You can see that it says Threads • Commented)

![Screenshot_20241214-055643](https://github.com/user-attachments/assets/558d38a3-ff58-4ac1-a62b-724a29a7f250)

### Version

0.7.0

### What platform(s) are you seeing the problem on?

Android

### Additional context

It also breaks a lot of other stuff, like when clicking on a magazine it shows all posts from all magazines

**Comment by jwr1** [comment]
I've looked into it (for several hours), and unforturently, it seems having the default sort different for the tabs is way harder than it should be. If you don't use tabs for the feed type, the sort does change correctly at least.

**Comment by jwr1** [comment]
Alright, I finally figured out something. Now, if the Feed type is set to use Tabs, then each tab has its correct Feed sort passed in. I will mention though, the way this was done does make it so that if you change the Feed sort from the default while using one Feed type, then it will also change for the other; but as long as you don't change the Feed sort, then each Feed type will use its correct corresponding Feed sort.

Fixed in ed0eb2f686ff08147915e36b447912ce0e64c7b0.
